parameters:
    guzzle:
        timeout: "%guzzle.timeout%"
        connect_timeout: "%guzzle.connect_timeout%"

    auth.vk:
        app_id: '%auth.vk.app_id%'
        username: '%auth.vk.username%'
        password: '%auth.vk.password%'
        scope: '%auth.vk.scope%'
        version: '%auth.vk.version%'

    publish.vk:
        user_id: '%publish.vk.user_id%'
        group_id: '%publish.vk.group_id%'

services:

#odm ==================================================================
    dbal.hot:
       class: ODM\DBAL
       arguments:
           - "%database.hot.host%"
           - "%database.hot.port%"
           - "%database.hot.name%"

    dbal.cold:
       class: ODM\DBAL
       arguments:
           - "%database.cold.host%"
           - "%database.cold.port%"
           - "%database.cold.name%"
           
    dm.hot:
       class: ODM\DocumentManager\DocumentManagerFactory
       arguments:
           - "@dbal.hot"

    dm.cold:
       class: ODM\DocumentManager\DocumentManagerFactory
       arguments:
           - "@dbal.cold"

#odm ==================================================================


# model document ======================================================

    model.document.black_list:
       class: AppBundle\Model\Document\BlackList\BlackListModel
       arguments:
           - '@dm.hot'

    model.document.city:
       class: AppBundle\Model\Document\City\CityModel
       arguments:
           - '@dm.hot'

    model.document.parse_list:
       class: AppBundle\Model\Document\ParseList\ParseListModel
       arguments:
           - '@dm.hot'

    model.document.publish_list:
       class: AppBundle\Model\Document\PublishList\PublishListModel
       arguments:
           - '@dm.hot'

    model.document.note:
       class: AppBundle\Model\Document\Note\NoteModel
       arguments:
           - '@dm.hot'
           - '@dm.cold'

    model.document.subway:
       class: AppBundle\Model\Document\City\SubwayModel
       arguments:
           - '@dm.hot'

# model document =====================================================


#request =============================================================

    request.client:
        class: AppBundle\Request\Client
        arguments:
            - "%guzzle%"

    request.tomita:
        class: AppBundle\Request\TomitaRequest
        arguments:
            - "@request.client"
            - "%request.base_uri.tomita%"

    request.public.vk:
        class: AppBundle\Request\VkPublicRequest
        arguments:
            - "@request.client"
            - "%request.base_uri.vk%"
            - '%auth.vk.version%'

    request.private.vk:
        class: AppBundle\Request\VkPrivateRequest
        arguments:
            - '@auth.vk'
            - "@request.client"
            - "%request.base_uri.vk%"
            - '%auth.vk.version%'

    auth.vk:
        class: Mrsuh\Service\AuthService
        arguments:
            - "%auth.vk%"

#request =============================================================


#parser ==============================================================

    parser.contact.factory:
        class: AppBundle\Model\Logic\Parser\Contact\ContactParserFactory

    parser.datetime.factory:
        class: AppBundle\Model\Logic\Parser\DateTime\DateTimeParserFactory

    parser.description.factory:
        class: AppBundle\Model\Logic\Parser\Description\DescriptionParserFactory

    parser.photo.factory:
        class: AppBundle\Model\Logic\Parser\Photo\PhotoParserFactory

    parser.id.factory:
        class: AppBundle\Model\Logic\Parser\Id\IdParserFactory

#parser =============================================================


#explorer ============================================================

    explorer.user.factory:
        class: AppBundle\Model\Logic\Explorer\User\UserExplorerFactory
        arguments:
            - "@request.public.vk"

    explorer.subway:
        class: AppBundle\Model\Logic\Explorer\Subway\SubwayExplorer
        arguments:
            - "@model.document.subway"

    explorer.tomita:
        class: AppBundle\Model\Logic\Explorer\Tomita\TomitaExplorer
        arguments:
            - "@request.tomita"

#explorer ============================================================


#collector ===========================================================

    collector.factory:
        class: AppBundle\Model\Logic\Collector\CollectorFactory
        arguments:
            - '@request.public.vk'
            - '@logger'
            - '%dir.tmp%'

#collector ===========================================================


#filter ==============================================================

    filter.unique.external_id:
        class: AppBundle\Model\Logic\Filter\ExternalIdUniqueFilter
        arguments:
            - "@dm.hot"

    filter.black_list.description:
        class: AppBundle\Model\Logic\Filter\DescriptionBlackListFilter
        arguments:
            - "@model.document.black_list"

    filter.black_list.person:
        class: AppBundle\Model\Logic\Filter\PersonBlackListFilter
        arguments:
            - "@model.document.black_list"

    filter.black_list.phone:
        class: AppBundle\Model\Logic\Filter\PhoneBlackListFilter
        arguments:
            - "@model.document.black_list"

    filter.expire.date:
        class: AppBundle\Model\Logic\Filter\DateExpireFilter

    filter.unique.description:
        class: AppBundle\Model\Logic\Filter\DescriptionUniqueFilter
        arguments:
            - "@dm.hot"

    filter.unique:
        class: AppBundle\Model\Logic\Filter\UniqueFilter
        arguments:
            - "@dm.hot"
#filter ==============================================================


#publiser ============================================================

    publisher.vk:
        class: AppBundle\Model\Logic\Publisher\VkPublisher
        arguments:
            - '@request.private.vk'
            - "@dm.hot"
            - "@logger"
            - '%publish.vk%'

#publiser ============================================================


#queue ===============================================================


    queue.collect.producer:
        class: AppBundle\Queue\Producer\CollectProducer
        arguments:
            - '@queue.collect.consumer'

    queue.collect.consumer:
        class: AppBundle\Queue\Consumer\CollectConsumer
        arguments:
            - '@parser.datetime.factory'
            - '@parser.description.factory'
            - '@parser.photo.factory'
            - '@parser.contact.factory'
            - '@parser.id.factory'

            - '@filter.expire.date'
            - '@filter.unique.description'
            - '@filter.unique'
            - "@filter.unique.external_id"
            - "@filter.black_list.description"
            - "@filter.black_list.person"
            - "@filter.black_list.phone"

            - '@explorer.subway'
            - '@explorer.tomita'
            - '@explorer.user.factory'

            - '@publisher.vk'

            - '@model.document.note'
            - '@logger'

#queue ===============================================================