parameters:
    guzzle:
        timeout: "%guzzle.timeout%"
        connect_timeout: "%guzzle.connect_timeout%"

services:

#odm ==================================================================

    dbal.hot:
       class: ODM\DBAL
       arguments:
           - "%database.hot.host%"
           - "%database.hot.port%"
           - "%database.hot.name%"

    dbal.cold:
       class: ODM\DBAL
       arguments:
           - "%database.cold.host%"
           - "%database.cold.port%"
           - "%database.cold.name%"
           
    dm.hot:
       class: ODM\DocumentManager\DocumentManagerFactory
       arguments:
           - "@dbal.hot"

    dm.cold:
       class: ODM\DocumentManager\DocumentManagerFactory
       arguments:
           - "@dbal.cold"

#odm ==================================================================


# model document ======================================================

    model.document.black_list:
       class: AppBundle\Model\Document\BlackList\BlackListModel
       arguments:
           - '@dm.hot'

    model.document.city:
       class: AppBundle\Model\Document\City\CityModel
       arguments:
           - '@dm.hot'

    model.document.parse.record:
       class: AppBundle\Model\Document\Parse\Record\RecordModel
       arguments:
           - '@dm.hot'

    model.document.parse.app:
        class: AppBundle\Model\Document\Parse\App\AppModel
        arguments:
            - '@dm.hot'

    model.document.publish.record:
       class: AppBundle\Model\Document\Publish\Record\RecordModel
       arguments:
           - '@dm.hot'

    model.document.publish.user:
       class: AppBundle\Model\Document\Publish\User\UserModel
       arguments:
           - '@dm.hot'

    model.document.note:
       class: AppBundle\Model\Document\Note\NoteModel
       arguments:
           - '@dm.hot'
           - '@dm.cold'

    model.document.subway:
       class: AppBundle\Model\Document\City\SubwayModel
       arguments:
           - '@dm.hot'

# model document =====================================================


#request =============================================================

    request.client:
        class: AppBundle\Request\Client
        arguments:
            - "%guzzle%"

    request.tomita:
        class: AppBundle\Request\TomitaRequest
        arguments:
            - "@request.client"
            - "%request.base_uri.tomita%"

    request.public.vk:
        class: AppBundle\Request\VkPublicRequest
        arguments:
            - "@request.client"

#request =============================================================


#parser ==============================================================

    parser.contact.factory:
        class: AppBundle\Model\Logic\Parser\Contact\ContactParserFactory

    parser.datetime.factory:
        class: AppBundle\Model\Logic\Parser\DateTime\DateTimeParserFactory

    parser.description.factory:
        class: AppBundle\Model\Logic\Parser\Description\DescriptionParserFactory

    parser.photo.factory:
        class: AppBundle\Model\Logic\Parser\Photo\PhotoParserFactory

    parser.id.factory:
        class: AppBundle\Model\Logic\Parser\Id\IdParserFactory

#parser =============================================================


#explorer ============================================================

    explorer.user.factory:
        class: AppBundle\Model\Logic\Explorer\User\UserExplorerFactory
        arguments:
            - "@request.public.vk"

    explorer.subway.factory:
        class: AppBundle\Model\Logic\Explorer\Subway\SubwayExplorerFactory
        arguments:
            - "@model.document.subway"

    explorer.tomita:
        class: AppBundle\Model\Logic\Explorer\Tomita\TomitaExplorer
        arguments:
            - "@request.tomita"

#explorer ============================================================


#collector ===========================================================

    collector.factory:
        class: AppBundle\Model\Logic\Collector\CollectorFactory
        arguments:
            - '@request.public.vk'
            - '@model.document.parse.app'
            - '@logger'
            - '%dir.tmp%'

#collector ===========================================================


#filter ==============================================================

    filter.unique.external_id:
        class: AppBundle\Model\Logic\Filter\ExternalIdUniqueFilter
        arguments:
            - "@dm.hot"

    filter.black_list.description:
        class: AppBundle\Model\Logic\Filter\DescriptionBlackListFilter
        arguments:
            - "@model.document.black_list"

    filter.black_list.person:
        class: AppBundle\Model\Logic\Filter\PersonBlackListFilter
        arguments:
            - "@model.document.black_list"

    filter.black_list.phone:
        class: AppBundle\Model\Logic\Filter\PhoneBlackListFilter
        arguments:
            - "@model.document.black_list"

    filter.expire.date:
        class: AppBundle\Model\Logic\Filter\DateExpireFilter

    filter.unique.description:
        class: AppBundle\Model\Logic\Filter\DescriptionUniqueFilter
        arguments:
            - "@dm.hot"

    filter.unique:
        class: AppBundle\Model\Logic\Filter\UniqueFilter
        arguments:
            - "@dm.hot"

#filter ==============================================================


#publiser ============================================================

    publisher.factory:
        class: AppBundle\Model\Logic\Publisher\PublisherFactory
        arguments:
            - '@request.client'
            - "@model.document.subway"
            - "@model.document.publish.user"
            - "@model.document.note"
            - "@logger"

#publiser ============================================================


#queue ===============================================================


    queue.collect.producer:
        class: AppBundle\Queue\Producer\CollectProducer
        arguments:
            - '@queue.collect.consumer'

    queue.collect.consumer:
        class: AppBundle\Queue\Consumer\CollectConsumer
        arguments:
            - '@parser.datetime.factory'
            - '@parser.description.factory'
            - '@parser.photo.factory'
            - '@parser.contact.factory'
            - '@parser.id.factory'

            - '@filter.expire.date'
            - '@filter.unique.description'
            - '@filter.unique'
            - "@filter.unique.external_id"
            - "@filter.black_list.description"
            - "@filter.black_list.person"
            - "@filter.black_list.phone"

            - '@explorer.subway.factory'
            - '@explorer.tomita'
            - '@explorer.user.factory'

            - '@queue.publish.producer'

            - '@model.document.note'
            - '@logger'

    queue.publish.producer:
        class: AppBundle\Queue\Producer\PublishProducer
        arguments:
            - '@queue.publish.consumer'

    queue.publish.consumer:
        class: AppBundle\Queue\Consumer\PublishConsumer
        arguments:
            - "@publisher.factory"
            - "@model.document.publish.record"
            - "@model.document.note"
            - "@logger"

#queue ===============================================================