parameters:
    guzzle:
        timeout: "%guzzle.timeout%"
        connect_timeout: "%guzzle.connect_timeout%"

services:

#odm ==================================================================

    dbal:
       class: ODM\DBAL
       arguments:
           - "%database.host%"
           - "%database.port%"
           - "%database.name%"
           
    dm:
       class: ODM\DocumentManager\DocumentManagerFactory
       arguments:
           - "@dbal"

#odm ==================================================================


# model document ======================================================

    model.document.black_list:
       class: AppBundle\Model\Document\BlackList\BlackListModel
       arguments:
           - '@dm'

    model.document.city:
       class: AppBundle\Model\Document\City\CityModel
       arguments:
           - '@dm'

    model.document.parse.record:
       class: AppBundle\Model\Document\Parse\Record\RecordModel
       arguments:
           - '@dm'

    model.document.parse.app:
        class: AppBundle\Model\Document\Parse\App\AppModel
        arguments:
            - '@dm'

    model.document.publish.record:
       class: AppBundle\Model\Document\Publish\Record\RecordModel
       arguments:
           - '@dm'

    model.document.publish.user:
       class: AppBundle\Model\Document\Publish\User\UserModel
       arguments:
           - '@dm'

    model.document.note:
       class: AppBundle\Model\Document\Note\NoteModel
       arguments:
           - '@dm'

    model.document.subway:
       class: AppBundle\Model\Document\City\SubwayModel
       arguments:
           - '@dm'

# model document =====================================================


#request =============================================================

    request.client:
        class: AppBundle\Request\Client
        arguments:
            - "%guzzle%"

    request.tomita:
        class: AppBundle\Request\TomitaRequest
        arguments:
            - "@request.client"
            - "%request.base_uri.tomita%"

    request.public.vk:
        class: AppBundle\Request\VkPublicRequest
        arguments:
            - "@request.client"

    request.avito:
        class: AppBundle\Request\AvitoRequest
        arguments:
            - "@request.client"
            - "@logger"
            - "%path.proxy_list%"

#request =============================================================


#parser ==============================================================

    parser.contact_id.factory:
        class: AppBundle\Model\Logic\Parser\ContactId\ContactIdParserFactory

    parser.contact_name.factory:
        class: AppBundle\Model\Logic\Parser\ContactName\ContactNameParserFactory
        arguments:
            - "@explorer.user.factory"

    parser.subway.factory:
        class: AppBundle\Model\Logic\Parser\Subway\SubwayParserFactory
        arguments:
            - "@explorer.subway.factory"

    parser.datetime.factory:
        class: AppBundle\Model\Logic\Parser\DateTime\DateTimeParserFactory

    parser.description.factory:
        class: AppBundle\Model\Logic\Parser\Description\DescriptionParserFactory

    parser.photo.factory:
        class: AppBundle\Model\Logic\Parser\Photo\PhotoParserFactory

    parser.id.factory:
        class: AppBundle\Model\Logic\Parser\Id\IdParserFactory

    parser.link.factory:
        class: AppBundle\Model\Logic\Parser\Link\LinkParserFactory

    parser.type.factory:
        class: AppBundle\Model\Logic\Parser\Type\TypeParserFactory
        arguments:
            - "@explorer.tomita"

    parser.price.factory:
        class: AppBundle\Model\Logic\Parser\Price\PriceParserFactory
        arguments:
            - "@explorer.tomita"

    parser.phone.factory:
        class: AppBundle\Model\Logic\Parser\Phone\PhoneParserFactory
        arguments:
            - "@explorer.tomita"

#parser =============================================================


#explorer ============================================================

    explorer.user.factory:
        class: AppBundle\Model\Logic\Explorer\User\UserExplorerFactory
        arguments:
            - "@request.public.vk"

    explorer.subway.factory:
        class: AppBundle\Model\Logic\Explorer\Subway\SubwayExplorerFactory
        arguments:
            - "@model.document.subway"

    explorer.tomita:
        class: AppBundle\Model\Logic\Explorer\Tomita\TomitaExplorer
        arguments:
            - "@request.tomita"

#explorer ============================================================


#collector ===========================================================

    collector.factory:
        class: AppBundle\Model\Logic\Collector\CollectorFactory
        arguments:
            - '@request.public.vk'
            - '@request.avito'
            - '@model.document.parse.app'
            - '@parser.id.factory'
            - '@parser.link.factory'
            - '@parser.datetime.factory'
            - '@logger'
            - '%dir.tmp%'
            - '%request.vk.wall.last_hours%'

#collector ===========================================================


#filter ==============================================================

    filter.black_list.description:
        class: AppBundle\Model\Logic\Filter\BlackList\DescriptionFilter
        arguments:
            - "@model.document.black_list"

    filter.black_list.person:
        class: AppBundle\Model\Logic\Filter\BlackList\PersonFilter
        arguments:
            - "@model.document.black_list"

    filter.black_list.phone:
        class: AppBundle\Model\Logic\Filter\BlackList\PhoneFilter
        arguments:
            - "@model.document.black_list"


    filter.cleaner.description:
        class: AppBundle\Model\Logic\Filter\Cleaner\DescriptionFilter
        arguments:


    filter.expire.date:
        class: AppBundle\Model\Logic\Filter\Expire\DateFilter


    filter.unique.id:
        class: AppBundle\Model\Logic\Filter\Unique\IdFilter
        arguments:
            - "@dm"

    filter.unique.description:
        class: AppBundle\Model\Logic\Filter\Unique\DescriptionFilter
        arguments:
            - "@dm"

    filter.unique.note:
        class: AppBundle\Model\Logic\Filter\Unique\NoteFilter
        arguments:
            - "@dm"

#filter ==============================================================


#publiser ============================================================

    publisher.factory:
        class: AppBundle\Model\Logic\Publisher\PublisherFactory
        arguments:
            - '@request.client'
            - "@model.document.subway"
            - "@model.document.publish.user"
            - "@model.document.note"
            - "@logger"
        tags:
            - { name: monolog.logger, channel: consumer_publish }

#publiser ============================================================


#queue ===============================================================


    queue.collect.producer:
        class: AppBundle\Queue\Producer\CollectProducer
        arguments:
            - '%queue.host%'
            - '%queue.port%'

    queue.collect.consumer:
        class: AppBundle\Queue\Consumer\CollectConsumer
        arguments:
            - '@model.document.note'
            - '@filter.unique.id'
            - '@filter.unique.note'
            - '@filter.unique.description'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: consumer_collect }

    queue.publish.producer:
        class: AppBundle\Queue\Producer\PublishProducer
        arguments:
            - '%queue.host%'
            - '%queue.port%'

    queue.publish.consumer:
        class: AppBundle\Queue\Consumer\PublishConsumer
        arguments:
            - "@publisher.factory"
            - "@model.document.publish.record"
            - "@model.document.note"
            - "@model.document.city"
            - "@logger"
        tags:
            - { name: monolog.logger, channel: consumer_publish }

    queue.parse.producer:
        class: AppBundle\Queue\Producer\ParseProducer
        arguments:
            - '%queue.host%'
            - '%queue.port%'

    queue.parse.consumer:
        class: AppBundle\Queue\Consumer\ParseConsumer
        arguments:
            - '@parser.description.factory'
            - '@parser.photo.factory'
            - '@parser.contact_name.factory'
            - '@parser.contact_id.factory'
            - '@parser.type.factory'
            - '@parser.price.factory'
            - '@parser.phone.factory'
            - '@parser.subway.factory'

            - '@filter.expire.date'
            - '@filter.unique.description'
            - '@filter.unique.note'
            - "@filter.unique.id"
            - "@filter.black_list.description"
            - "@filter.black_list.person"
            - "@filter.black_list.phone"
            - "@filter.cleaner.description"

            - '@queue.collect.producer'
            - '@queue.publish.producer'

            - '@model.document.note'
            - '@logger'

        tags:
            - { name: monolog.logger, channel: consumer_parse }

#queue ===============================================================